### ISSUE TITLE
Generating file without 'Chunk' and 'Source map'

### ISSUE THREAD

**Issue by wellyshen** [shellscape/webpack-manifest-plugin#136]
Thank you for this library. Is there any way to exclude the 'chunk' and 'source map' key from the generated `.json` file?

Current this plugin will includes all of them:
```javascript
{
  "0.d6ddf792.chunk.css": "/assets/0.d6ddf792.chunk.css",
  "0.d6ddf792.chunk.js": "/assets/0.d6ddf792.chunk.js",
  "0.d6ddf792.chunk.css.map": "/assets/0.d6ddf792.chunk.css.map",
  "0.d6ddf792.chunk.js.map": "/assets/0.d6ddf792.chunk.js.map",
  "1.80109e15.chunk.css": "/assets/1.80109e15.chunk.css",
  "1.80109e15.chunk.js": "/assets/1.80109e15.chunk.js",
  "1.80109e15.chunk.css.map": "/assets/1.80109e15.chunk.css.map",
  "1.80109e15.chunk.js.map": "/assets/1.80109e15.chunk.js.map",
  "vendors~main.js": "/assets/vendors~main.39b558ef.chunk.js",
  "vendors~main.js.map": "/assets/vendors~main.39b558ef.chunk.js.map",
  "main.css": "/assets/main.0c770436.css",
  "main.js": "/assets/main.0c770436.js",
  "main.css.map": "/assets/main.0c770436.css.map",
  "main.js.map": "/assets/main.0c770436.js.map"
}
```

**Comment by mastilver** [comment]
Yes, you can use the `filter` options: https://github.com/danethurber/webpack-manifest-plugin#optionsfilter

i wonder if we could add a `isSourceMap` property?

**Comment by wellyshen** [comment]
@mastilver The filter document isn't very clearly. Can you give a quickly example? Sure the `isSourceMap ` would be convenience for us 👍

**Comment by jimblue** [comment]
Agree with @wellyshen, doc could be improved on that point.
To filter out sourcemap I've try this which is not working:

```js
filter: {
  name: '*.map'
}

**Comment by mastilver** [comment]
@jimblue  

It takes a function, so something along the lines of:
```
filter({path}) {
  return path.test(/.map^/)
}
```

Could you send a PR to improve the doc?

**Comment by jimblue** [comment]
It's not working:

```js
new ManifestPlugin({
    filter: ({ path }) => {
        return path.test(/.map^/)
    }
})
```

return this error: **path.test is not a function**

**Comment by mastilver** [comment]
Fixed it, I haven't tested the code, so it might not work either ;)

**Comment by jimblue** [comment]
Just decide to move to [webpack-assets-manifest](https://github.com/webdeveric/webpack-assets-manifest).
It's much more powerfull for my needs as I only use manifest.json to load assets from a php framework. 
Thanks for your help @mastilver !

**Comment by wellyshen** [comment]
Hi Guys, I used `isInitial` to filter out all chunks. But source-maps still there.

**Comment by adamzasah** [comment]
@jimblue I have it like this
```javascript
new ManifestPlugin({
    fileName: "manifest.json",
    filter: ({name}) => !name.endsWith('.map')
})
```
and it works flawlessly.

**Comment by wulv** [comment]
`{filter: (fileDes) => fileDes.isInitial && !fileDes.name.endsWith('.map')}`
