### ISSUE TITLE
Generate with compilation object

### ISSUE THREAD

**Issue by jscheid** [shellscape/webpack-manifest-plugin#137]
Hi, I'm looking after [webpack-subresource-integrity](https://github.com/waysact/webpack-subresource-integrity). We've had several requests for a feature that would let people export the per-asset integrity values as JSON, but I think a better solution might be to make it easy to use your plugin together with ours.

One simple solution would be if you could pass the `compilation` object as an additional argument to `generate`.  We'd then export a default generator function and advise people to use it like so:

```js
new ManifestPlugin({
  generate: SriPlugin.manifestGenerator(),
})
```

Our generator function would find the integrity values from the `compilation` object and generate something like `{ path: '...', integrity: '...' }` based on it.

What do you think?

**Comment by mastilver** [comment]
I think that sounds great!! :)

Anything we should add from https://github.com/danethurber/webpack-manifest-plugin#hooks-options to help you implement that?

**Comment by jscheid** [comment]
I guess if it had the original compilation asset that would be ideal. It would have to be the one from `compilation.assets`, not the one from `compilation.getStats().toJson().assets` because there isn't a good way yet for adding custom data to the stats JSON.

**Comment by shellscape** [comment]
We've added support for the `beforeEmit` hook in f62ca8b273dcba5911e5f08814595c949120b6af. Please see the `Compiler Hooks` section in the README.
