### ISSUE TITLE
V3

### ISSUE THREAD

**Issue by mastilver** [shellscape/webpack-manifest-plugin#153]
Changes:
- [ ] drop support for webpack 2 and 3

Possible changes (needs to be discussed):
- [ ] revert https://github.com/danethurber/webpack-manifest-plugin/pull/140 to fix  https://github.com/danethurber/webpack-manifest-plugin/issues/144 ?
- [ ] revert https://github.com/danethurber/webpack-manifest-plugin/pull/142 ? After reflection, it doesn't feel natural; Does it need to be removed or does an options needs to be added (IMO only if absolutely necessary)
- [ ] name change: https://github.com/danethurber/webpack-manifest-plugin/issues/145

Please suggest other changes, I will add it to the list if relevant

**Comment by ndelage** [comment]
Including this PR would be great: https://github.com/danethurber/webpack-manifest-plugin/pull/174

After applying the change I've seen the time spent in this plugin drop from > 2 seconds to a few thousands of a second!

**Comment by shellscape** [comment]
Please see #222 for status and current planning.
