### ISSUE TITLE
Incompatibility with the latest version of mini-css-extract-plugin (0.4.3)

### ISSUE THREAD

**Issue by Lyrkan** [shellscape/webpack-manifest-plugin#167]
Hi there,

It seems that there is an issue when using the latest versions of the `mini-css-extract-plugin` and this plugin together.

We have a test case in [Webpack Encore](https://github.com/symfony/webpack-encore/) with the following stylesheet:

```css
// roboto_font.css
@font-face {
    font-family: 'Roboto';
    src: url('./../fonts/Roboto.woff2') format('woff2');
}
```

When we require that file with `mini-css-extract-plugin@0.4.2` everything works as intended, however with `mini-css-extract-plugin@0.4.3` we get the following manifest (don't mind the other entries):

```json
{
	"build/bg.css": "/build/bg.css",
	"build/font.css": "/build/font.css",
	"build/main.js": "/build/main.js",
	"build/runtime.js": "/build/runtime.js",
	"build/images/another_bg_image.css": "/build/images/symfony_logo.ea1ca6f7.png",
	"build/fonts/roboto_font.css": "/build/fonts/Roboto.9896f773.woff2"
}
```

As you can see, instead of having a "`build/fonts/Roboto.woff2`" key, we get "`build/fonts/roboto_font.css`"... which doesn't feel right at all :)

I tracked down the issue to this PR: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/177#issuecomment-422571408

Apparently `webpack-assets-manifest` was also affected and managed to solve it (https://github.com/webdeveric/webpack-assets-manifest/issues/39).

**Comment by electrocnic** [comment]
> The current workaround for this is to force the dependency to 0.4.2 through yarn resolutions.

This did not help in my case :(
Using "mini-css-extract-plugin": "^0.5.0",

**Comment by a573367014** [comment]
> > 目前的解决方法是通过纱线分辨率强制依赖性为0.4.2。
> 
> 这对我的情况没有帮助:( 
> 使用“mini-css-extract-plugin”：“^ 0.5.0”，

me too

**Comment by fernandopasik** [comment]
I mean in package.json have a resolutions key (this only works with yarn, not supported by npm)

```
{
  "devDependencies": {
    "mini-css-extract-plugin": "^0.4.2"
  },
  "resolutions": {
     "mini-css-extract-plugin": "0.4.2"
  }
}
```

for npm I guess you can force the version and that's it

```
{
  "devDependencies": {
    "mini-css-extract-plugin": "0.4.2"
  }
}
```

**Comment by harryfinn** [comment]
Thanks @fernandopasik, reverting to `0.4.2` fixed an issue in my webpack build whereby in development mode, font assets were removed after first rebuild and not being saved in the manifest correctly!

**Comment by hershmire** [comment]
Are there any plans for webpack-manifest-plugin to have a permanent fix?

**Comment by mauricesnip** [comment]
I'm having this issue with `2.0.4` in combination with `mini-css-extract-plugin` `0.7.0` and `0.8.0`. Indeed, reverting to `mini-css-extract-plugin@0.4.2` fixes this. Did anyone manage to get this to work with the recent versions of `mini-css-extract-plugin`?

**Comment by TheDutchCoder** [comment]
I can confirm this issue.

it also happens with PostCSS and ExtractCssPlugin, where (for example) fonts end up as a single entry like this:

```
"fonts/app.pcss": "/static/redesign/fonts/Nimbus-Sans-Novus-Semibold.woff",
```

Both the key and value make no sense.

**Comment by mastilver** [comment]
#176 is available on `3.0.0-rc.0`

**Comment by pascalw** [comment]
I was running into this issue and can confirm that `3.0.0-rc.0` solves it.

**Comment by alex996** [comment]
Unfortunately, the issue still occurs with the current `mini-css-extract-plugin` (`v1.3.1`). I've put up a minimal repro in [this repository](https://github.com/alex996/webpack-manifest-demo/tree/mini-css-extract-plugin#readme), but in short, the plugin emits incorrect keys for CSS files, for example:

```jsonc
{
  "main.css": "style.b248c6e8f370b3bc8646.css", // <--- key should be "style.css"
  "main.js": "main.3cf1156c43d58afb8952.js"
}
```

 @shellscape Thanks in advance to your attention; I can create a separate issue if need be.

**Comment by shellscape** [comment]
@alex996  This is a webpack v5 issue. See #222

**Comment by shellscape** [comment]
v3.0.0 is published and should resolve this issue.
