### ISSUE TITLE
3.0 release plan

### ISSUE THREAD

**Issue by mastilver** [shellscape/webpack-manifest-plugin#195]
BREAKING CHANGES:
- [x] stop supporting node@6
- [x] stop support webpack 2 and 3
- [ ] fix #144

Fixes:
- [x] fix #167 

Chores:
- [x] use `MiniCssExtractPlugin` instead of `ExtractTextPlugin` in tests so it's easier to track and fix issues like #176

**Comment by piecyk** [comment]
@mastilver how can i help to land this ?

**Comment by shellscape** [comment]
Hey folks, please see #222 for updates on v5 support.
