### ISSUE TITLE
Deprecation of NormalModuleLoader hook

### ISSUE THREAD

**Issue by Aghassi** [shellscape/webpack-manifest-plugin#202]
https://github.com/danethurber/webpack-manifest-plugin/blob/4e02e21a61f2a7e41d36b0564d45c5f4932b0615/lib/plugin.js#L246

Webpack 5 throws a deprecation on this line, and I believe the remediation is to use `NormalModule.getCompilationHooks` as per the message I'm getting:

```
(node:17698) DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
```

**Comment by mastilver** [comment]
yes, we should try to reduce as much DeprecationWarning as possible, but we need to make sure the code is still compatible with v4

**Comment by shellscape** [comment]
Hey folks, please see #222 for updates on v5 support.
