### ISSUE TITLE
Programmatically get the manifest output

### ISSUE THREAD

**Issue by garygreen** [shellscape/webpack-manifest-plugin#207]
Would it be possible to use this plugin directly so that you can get the manifest output/object without having to write it to a file?

For example:

```js
const ManifestPlugin = require('webpack-manifest-plugin');

plugins: [
    {
        apply: function(compiler) {
            const manifest = ManifestPlugin.getFromCompiler(compiler);

            // Do something with the manifest, e.g. write it to a service worker sw.js file
        }
    }
]
```

Our use case is that we want to write the manifest for use in a service worker file.

Maybe the `generate` option is useful here because if the compilation changes through watch then maybe that would be a better approach? Possibly related to: https://github.com/danethurber/webpack-manifest-plugin/issues/137

**Comment by gdvsbp** [comment]
I'm interested in this functionality as well for a complex multi-entrypoint/multi-chunk build that can embed different functionality at runtime based on a small embed script. For that script to have access to the compiler output would be a ton of help. I recognize that I could accomplish this through a secondary build for the embed script that runs after the primary build, but I'd much rather avoid that complexity and be able to wrap it up under one.

**Comment by garygreen** [comment]
@gdvsbp you may find this code useful... I've basically wrote our own plugin which generates a manifest file of the chunk information under a new file `manifest.json` - you can adapt the code to change the format or pick our specific chunks.

This is for Webpack 4, not sure if it needs to be adapted for later version of Webpack:

### build/manifest.js
```js
const path = require('path');

function GenerateManifest() {
    GenerateManifest.prototype.apply = function(compiler) {

    compiler.hooks.emit.tapAsync('generate-manifest-plugin', function(compilation, callback) {
        var manifest = {
            // Get output path without leading and trailing slashes
            path: compilation.outputOptions.publicPath.replace(/^\//, '').replace(/\/$/, ''),
            chunks: {},
            assets: {}
        };

        var getFileDetails = function(chunk, file) {
            return {
                path: file,
                ext: path.extname(file).substr(1)
            }
        };

        compilation.chunks.forEach(function(chunk) {
            if (chunk.isOnlyInitial()) {
                manifest.chunks[chunk.name] = chunk.files.map((file) => getFileDetails(chunk, file));
            }
        });

        var source = JSON.stringify(manifest);

        compilation.assets['manifest.json'] = {
            source: function() {
                return source;
            },

            size: function() {
                return source.length;
            }
        };
        
        callback();
    }.bind(this));
};

module.exports = GenerateManifest;
```

Output format example of `manifest.json`:

```json
{
  "path": "dist-admin",
  "chunks": {
    "admin": [
      {
        "path": "admin-8ebaecbefb148a102400.css",
        "ext": "css"
      },
      {
        "path": "js/admin-6413be24c62724ad0bc1.js",
        "ext": "js"
      }
    ],
    "admin-tab": [
      {
        "path": "js/admin-tab-b232dd435ee11580f3c5.js",
        "ext": "js"
      }
    ],
    "vendor": [
      {
        "path": "js/vendor-003306aa5189662769bf.js",
        "ext": "js"
      }
    ]
  },
  "assets": {}
}
```

### Usage:
```js
const GenerateManifest = require('./build/manifest');

// Under plugins array in webpack add:
new GenerateManifest();
```

.... we personally use this manifest.json file for various things, such as cache invalidation, use in a service worker, etc.

**Comment by shellscape** [comment]
Closing this as there are a few workarounds shared which are reasonable. If none of these workarounds are satisfactory, please open a new `Feature` issue.
