### ISSUE TITLE
Manifest keys contain hashes in production build when using file-loader

### ISSUE THREAD

**Issue by mabeyj** [shellscape/webpack-manifest-plugin#209]
Files produced by file-loader contain hashes in their manifest keys only when running a production build (`webpack -p`). This doesn't happen when running `webpack -d`.

Example:

```json
// package.json
{
  "devDependencies": {
    "file-loader": "5.0.2",
    "webpack": "4.41.2",
    "webpack-cli": "3.3.10",
    "webpack-manifest-plugin": "2.2.0"
  }
}
```

```js
// webpack.config.js
const path = require("path");
const ManifestPlugin = require("webpack-manifest-plugin");

module.exports = {
  entry: "./index.js",
  output: {
    path: path.resolve(__dirname, "out"),
    publicPath: "/public/"
  },
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: "file-loader",
        options: {
          name: "[name].[contenthash].[ext]",
          outputPath: "images"
        }
      }
    ]
  },
  plugins: [new ManifestPlugin()]
};
```

```js
// index.js
import path from "./test.svg";
```

Manifest after running `webpack -d`:

```json
{
  "main.js": "/public/main.js",
  "images/test.svg": "/public/images/test.a584b560355112eaa168435c4860f5d8.svg"
}
```

Manifest after running `webpack -p`:

```json
{
  "main.js": "/public/main.js",
  "images/test.a584b560355112eaa168435c4860f5d8.svg": "/public/images/test.a584b560355112eaa168435c4860f5d8.svg"
}
```

**Comment by ElGigi** [comment]
It's a conflict with file-loader package version >= 5.0.0.
To fix temporary them:

```
// package.json
{
  "devDependencies": {
    "file-loader": ">=4.3.0 <5.0.0"
  }
}
```

**Comment by gpvidal** [comment]
Setting `file-loader` `esModule` option to `false` worked in my case:
```
{
  test: /\.svg$/,
  loader: "file-loader",
  options: {
      name: "[name].[contenthash].[ext]",
      outputPath: "images",
      esModule: false,
  }
}
```
Also works with `file-loader` 6.0.0 package version

**Comment by 4c0n** [comment]
@danethurber Do you plan on looking into this issue and supporting the es modules version of `file-loader`? It's causing quite a few issues. We're 8 months in and there are a lot of projects that depend on this plugin, `symfony/webpack-encore` is pretty widely used for example.

Not trying to be pushy or anything (well maybe a little ;) ), I mean "no" is also an answer. However I must say it would be nice to see some sort of response from you! :smiley:

**Comment by 4c0n** [comment]
Hi @danethurber is there any specific reason that you are ignoring this package and its issues? Maybe you don't want to maintain it anymore? Getting too many notfications? Not enough time? If you are please say so, then the other projects using your plugin can start making other plans. Now we're all kind of stuck in limbo, as you're not responding... :-1:

**Comment by danethurber** [comment]
hey @4c0n. there have been other maintainers on this project for the last couple years. i  haven't been involved. i'll try to track them down to see what the current state is

**Comment by 4c0n** [comment]
Thanks @danethurber hope we can resolve it :smile:

**Comment by 4c0n** [comment]
@mastilver You seem to have been involved in maintaining this package, could you perhaps shine some light on this issue?

**Comment by 4c0n** [comment]
I feel this package should be marked deprecated in npm. It is clearly no longer being maintained. Ghostware :jack_o_lantern: :ghost: 

@danethurber Could you help out there?

**Comment by shellscape** [comment]
Hey all! I've taken over maintenance of the plugin and am doing some housecleaning. For Issues over a year old without a reproduction, we're going to go the route of closing them first. However, they're not dead! If the issue is still pending and still a problem, please reply with a reproduction and we'll reopen post-haste. 

Please provide a reproduction by choosing one of the options below:

  1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
     Please use NPM for installing dependencies!
     These may take more time to triage than the other options.

  ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

**Comment by mabeyj** [comment]
@shellscape Here is a reproduction: https://repl.it/@jmabey/webpack-manifest-plugin-209

**Comment by shellscape** [comment]
Thanks for that. I took a look at the reproduction and think this may be related to #210, which I closed a little bit ago in https://github.com/shellscape/webpack-manifest-plugin/commit/5bad3ea98861ef750954e8c58ee6ea21d3592845. Please have a look at that commit and let me know if that resolves this issue as well.

**Comment by mabeyj** [comment]
Yep, can confirm that commit resolves this: https://repl.it/@jmabey/webpack-manifest-plugin-209-fixed

Thanks!
