### ISSUE TITLE
ManifestPlugin frequently serve old css files

### ISSUE THREAD

**Issue by paztis** [shellscape/webpack-manifest-plugin#220]
When using my project in dev mode, after a big of time, ManifestPlugin stops to update the contenthash in the filename
HtmlWebpackPlugin well do it: when I modify my scss code, webpack rebuilds it and new css files are well injected.
But the manifestPlugin is pointing to old css files and is never updated.

This frequently appears after long dev time
I also notice if when I switch my network without restarting the webpack-dev-server (perhaps there's a link between both)

**Comment by shellscape** [comment]
Hey @paztis, we just took this project out of a deprecated state and are starting to give it some attention. Unfortunately with issues unless you provide a reproduction, we probably can't help you. You can read https://git.io/fNzHA for instructions on creating a minimal reproduction. It's a good practice no matter which project you're interacting with.

**Comment by jkevingutierrez** [comment]
I'm having a similar error using webpack-dev-server. ManifestPluging is not reflecting the changes when I update a file using webpack-dev-server. I need to run the regular webpack command otherwise, ManifestPluging doesn't show the changes

**Comment by shellscape** [comment]
@jkevingutierrez you might want to open an issue with webpack-dev-server in that case. If it doesn't happen with regular webpack, but happens with dev-server, it's probably a dev-server issue.

I would also suggest giving `webpack-plugin-serve` a try. For most users, it's a superior experience https://github.com/shellscape/webpack-plugin-serve
