### ISSUE TITLE
Entrypoints feature

### ISSUE THREAD

**Issue by madflow** [shellscape/webpack-manifest-plugin#221]
Hello!

In two other assets plugins there is an "entrypoint" functionality:

* https://github.com/webdeveric/webpack-assets-manifest#entrypoints
> Include compilation.entrypoints in the manifest file.

* https://github.com/ztoben/assets-webpack-plugin#entrypoints
> If the 'entrypoints' option is given, the output will be limited to the entrypoints and the chunks associated with them.

As far as I can see - this plugin does not have this feature.

So the feature request would be:

I want to be able to configure 
* that the output is **limited** to only the entrypoints
* and that entrypoints are **added** to the output with a configurable key

**Comment by shellscape** [comment]
Thank you for the suggestion!

**Comment by shellscape** [comment]
@madflow we've updated and refactored the codebase in preparation for v3.0.0. Would you be interested in adding that feature with a pull request?

**Comment by madflow** [comment]
> @madflow we've updated and refactored the codebase in preparation for v3.0.0. Would you be interested in adding that feature with a pull request?

Sorry, I am not interested. In the meantime, I settled on another Asset/Manifest plugin.

**Comment by shellscape** [comment]
Thanks for letting us know.
