### ISSUE TITLE
[Webpack 5] Incorrect mappings with copy-webpack-plugin

### ISSUE THREAD

**Issue by alex996** [shellscape/webpack-manifest-plugin#228]
- Manifest Plugin Version: `^3.0.0-rc.0`
- Webpack Version: `^5.6.0` (latest to date)
- Operating System (or Browser): Ubuntu 20.04 / Chrome 86
- Node Version: `v14.13.1`
- Link to reproduction _(⚠️ read below)_: <https://github.com/alex996/webpack-manifest-demo/tree/copy-webpack-plugin>

### Use Case

Copying static asset files (e.g. images) using [`copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin). Not sure if this use case is supported (i.e. whether it's a bug report or a feature request), but this package does produce the mappings that are sadly incorrect.

### Expected Behavior

The key in `manifest.json` should match the original file name (and path), and _not_ include the resulting `contenthash`. For example, given an image `myimage.99217f7d9cb04497c0c92f3c0d0f82f1.png` the key should be `myimage.png`.

### Actual Behavior

The key is incorrect in that it also includes the `contenthash` making the mapping unusable and impractical.

### Additional Information

Please see the full details in the [readme of the repo](https://github.com/alex996/webpack-manifest-demo/tree/copy-webpack-plugin#readme).

**Comment by shellscape** [comment]
Same issue as #210, #208, and #167. (Please do remember to search before opening new issues)
