### ISSUE TITLE
ManifestPlugin is not a constructor 

### ISSUE THREAD

**Issue by Mati365** [shellscape/webpack-manifest-plugin#230]
```js
const ManifestPlugin = require('webpack-manifest-plugin');

new ManifestPlugin
```

causes the problem

**Comment by 0x78f1935** [comment]
```
        const { WebpackManifestPlugin } = require('webpack-manifest-plugin');

        new WebpackManifestPlugin({
            fileName: './manifest.json',
            publicPath: '/static/react/',
        }),
```

Works for me : )

**Comment by scott-ln** [comment]
I had this issue just now, and it turned out to be because `npm i webpack-manifest-plugin` had inexplicably installed version 2.2.0 (why?), which doesn't export the same way. `npm i webpack-manifest-plugin@latest` installed 4.0.2 and that fixed it. Hope this is of use to anyone else ending up here.

**Comment by Mahdiyeh** [comment]
> webpack-manifest-plugin

I have the version 4.0.2, but still the same issue.

**Comment by adilhas** [comment]
//this is package.json

"scripts": {
"build": "node scripts/copy_assets.js  &&  node_modules/.bin/webpack --config
webpack.config.prod.js",
},

//how to write this code in latest version

**Comment by noeloconnor** [comment]
having the same issues on 4.0.2 as well.

**Comment by shellscape** [comment]
Honestly people, read the documentation: https://github.com/shellscape/webpack-manifest-plugin#usage

Or check the code: https://github.com/shellscape/webpack-manifest-plugin/blob/master/src/index.ts#L65

Major version updates to packages contain *breaking changes*. That's semver 101 https://semver.org/
