### ISSUE TITLE
Manifest file is not taking compressed files

### ISSUE THREAD

**Issue by jkevingutierrez** [shellscape/webpack-manifest-plugin#231]
- Manifest Plugin Version: 3.0.0
- Webpack Version: 5.9.0
- Operating System (or Browser): macOS 10.15.7
- Node Version: 14.15.0
- Link to reproduction _(⚠️ read below)_: https://repl.it/@jkevingutierrez/manifest-plugin-repro#webpack.config.js

### Expected Behavior
Using [compression-webpack-plugin](https://github.com/webpack-contrib/compression-webpack-plugin) with webpack-manifest-plugin should include the compressed files generated by compression-webpack-plugin in the manifest.json file

```
{
  "input.js": "input.js",
  "input.js.gz": "input.js.gz"
}
```

### Actual Behavior
Files generated by compression-webpack-plugin are not included in the manifest.json file
```
{
  "input.js": "input.js"
}
```

### Additional Information

It was working before on Webpack v4 and manifest plugin v2: https://repl.it/@jkevingutierrez/manifest-plugin-repro-1#dist/manifest.json

**Comment by shellscape** [comment]
See #229 for the auto issue ( and please search issues )

Did this work in the previous version of this plugin on webpack v4?

**Comment by jkevingutierrez** [comment]
My bad, I just searched in opened issues.

About the compression problem, it was working before on Webpack v4:

https://repl.it/@jkevingutierrez/manifest-plugin-repro-1#dist/manifest.json

**Comment by shellscape** [comment]
No problem. I'll use your repro to make an integration test and work on this

**Comment by shellscape** [comment]
Unfortunately you're running into an early adoption problem :( Webpack v5 just isn't ready, and the official plugins aren't either. Please see this comment https://github.com/webpack/webpack/issues/11822#issuecomment-738121628 in a webpack core issue. They have some more work to do in order to get this to work like it did with Webpack v4.
