### ISSUE TITLE
Generated manifest seems not to consider to loading order of the resources

### ISSUE THREAD

**Issue by paztis** [shellscape/webpack-manifest-plugin#234]
- Manifest Plugin Version: 2.2.0
- Webpack Version: 4.44.2
- Operating System (or Browser): last chrome
- Node Version: 14
- Link to reproduction _(⚠️ read below)_:

Generated manifest file is not considering the loading order of the scripts
vendors~module.js are after module.js  
if we load all the script 1 by 1 from the manifest, the application crashes because the script order in not correct

### Expected Behavior
resources need to be in the correct order to be able to load correctly the application from it (like HTML webpack plugin do)

### Actual Behavior
if we load all the script 1 by 1 from the manifest, the application crashes because

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

  

> 🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@shellscape/manifest-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by Hirbod** [comment]
@shellscape sorry to hijack this closed issue, but I was searching for exactly this problem and I don't think that it does need any further explanation as you asked for (sorry if I got another opinion on this)

My issue is, that we use webpack to generate our whole frontend application which will be ported into a CMS. So far so good. 
In order to generate our html-head in our php template, I would like to parse the manifest.json and generate all those <link> and <script> entries, but the generated manifest is out of order and does not represent the same order as the HtmlPlugin injects them automatically. Is this the expected behavior or is there a way to get the exact order like the HTMLWebpackPlugin injects the assets into head?

**Comment by shellscape** [comment]
Open a new issue with a reproduction or I cannot help you. I simply lack the time to triage every issue unless folks provide a reproduction.

**Comment by paztis** [comment]
Hi

My usage was the same. I stop to use webpack-manifest-plugin for this need to replace it by HtmlRenderer plugin. This one allow you to create template pages in us. And on this code I catch the files and save them to other manifest file

**Comment by Hirbod** [comment]
@paztis would be lovely if you could share your code on this.

@shellscape I managed to create a repo, I will open a new issue

**Comment by paztis** [comment]
in the webpackconfig file
```
new HtmlWebpackPlugin({
                    template: PATH.resolve(TEMPLATE_PATH, 'index.html.js'),
                    templateParameters: {
                        rootContent: '<view-designer-app />'
                    },
                    filename: 'index.html',
                    chunks: [PACKAGE_JSON.name],
                    
                    // client libs declaration
                    clientLibsDeclaration: {
                        path: PATH.resolve(BUILD_FOLDER, 'client-libs.json')
                    }
                }),
```

in the template file index.html.js
I do the injection in a json file iwith FS.writeFileSync
```
module.exports = (context) => {
    const options = context.htmlWebpackPlugin.options;

    // serialize the injected files path in the clientLibs json file
    if (options.clientLibsDeclaration) {
        FS.mkdirSync(PATH.dirname(options.clientLibsDeclaration.path), {recursive: true});
        FS.writeFileSync(
            options.clientLibsDeclaration.path,
            JSON.stringify(context.htmlWebpackPlugin.files, null, 4)
        );
    }

    // return HTML template
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
</head>
<body>
    ${options.templateParameters.rootContent || '<div id="root"></div>'}
</body>
</html>
`;
};
```
