### ISSUE TITLE
ManifestPlugin is not a constructor error on build with Ubuntu 

### ISSUE THREAD

**Issue by thirionlogan** [shellscape/webpack-manifest-plugin#240]
- Manifest Plugin Version: 3.0.0
- Webpack Version: 4.44.2
- Operating System (or Browser): Ubuntu 18.04.5 LTS
- Node Version: 10.x and 14.x
- Link to reproduction _(⚠️ read below)_:  [Pull request with failing checks](https://github.com/thirionlogan/site-boilerplate/pull/20)

### Actual Behavior
checks are failing on the build step with this error: `TypeError: ManifestPlugin is not a constructor`. The failing command (`npm run build --if-present`) runs without any issues on a local windows 10 clone of the repo.

**Comment by shellscape** [comment]
Please always search the issues before opening a new one. https://github.com/shellscape/webpack-manifest-plugin/search?q=not+a+constructor&type=issues

https://github.com/shellscape/webpack-manifest-plugin#usage
