### ISSUE TITLE
Files generated by webpack plugins are not being added to the manifest file.

### ISSUE THREAD

**Issue by Levdbas** [shellscape/webpack-manifest-plugin#245]
- Manifest Plugin Version: 3.0.0
- Webpack Version: 5.15
- Operating System (or Browser): Ubuntu 20
- Node Version: 14.15
- Link to reproduction : https://github.com/Levdbas/manifest-error

### Expected Behavior
when running npm run dev index.asset.json, generated by @wordpress/dependency-extraction-webpack-plugin, is also added to the manifest file.

### Actual Behavior
index.asset.json is missing from manifest file.

### Additional Information

I've the same issue with other webpack plugins that emit files as well, but I have limited this repo to only one example.
Nice detail: when setting webpack to 4.46 and webpack-manifest-plugin to 2.2.0 and retry to run npm run dev index.asset.json does get added to the manifest file.

So it seems like the files like this outside the entry files are not being added to the manifest. Any idea?

**Comment by shellscape** [comment]
I'm stretched a little thin at the moment so would appreciate a PR to resolve this.

**Comment by Levdbas** [comment]
Okey, since I have little to no knowledge of the inner workings of this plugin/webpack I am kind of  hesitant with making a PR.

That being said, I dived into the code and found out the error occurs right here:
```javascript
if (webpack.version.startsWith("4")) {
      compiler.hooks.emit.tap(hookOptions, emit);
    } else {
      compiler.hooks.afterCompile.tap(hookOptions, (compilation) => {
        compilation.hooks.afterProcessAssets.tap(hookOptions, () =>
          emit(compilation)
        );
      });
    }
```

When removing the if/else alltogether and change it just to

```javascript
compiler.hooks.emit.tap(hookOptions, emit);
```

at least my test repo works again and the file does get added to the manifest.

I think you have a good reason for adding that if/else statement in the first place but it seems that emit hook is getting called too early or something. Hopefully this will point you in the right direction.

**Comment by shellscape** [comment]
Thanks for the extra info. I won't be working on this one but hopefully it helps someone in the community to contribute a fix.

**Comment by NovaLagnus** [comment]
@Levdbas Perhaps try the following in the else section. I think the inner emit might have lost its scope, depending on your js environment.

 compiler.hooks.afterCompile.tap(hookOptions, 
compilation.hooks.processAssets.tap(hookOptions, 
                                                               emit.bind(this, compilation))
                                                       .bind(this, compilation));

**Comment by Levdbas** [comment]
Hi @Levdbas see the comments on #246 . The updated hook for webpack 5 in version 3.0 is right but other plugins are still using the deprecated compiler.hooks.emit.tap hook. Those other plugins are generating assets after the manifest was generated.

**Comment by strarsis** [comment]
Different plugin (same functionality), but probably same reason: https://github.com/webdeveric/webpack-assets-manifest/issues/132
