### ISSUE TITLE
Missing v3.1.0 release/tag

### ISSUE THREAD

**Issue by mynameisbogdan** [shellscape/webpack-manifest-plugin#255]
Hello,

On [npmjs](https://www.npmjs.com/package/webpack-manifest-plugin/v/3.1.0) seems to be a v3.1.0 release, but no release or tag on this repository.

There's no way to compare the two last releases.

/cc @shellscape

**Comment by shellscape** [comment]
Pushed. I'll follow up with the release when I get the chance.

**Comment by mynameisbogdan** [comment]
Thank you.
