### ISSUE TITLE
File path has "auto" prefix with default publicPath on webpack 5

### ISSUE THREAD

**Issue by Artoria-0x04** [shellscape/webpack-manifest-plugin#265]
- Manifest Plugin Version: 3.1.1
- Webpack Version: 5.37.0
- Operating System (or Browser): Chrome v90
- Node Version: 14.5.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@Artoria/manifest-plugin-repro-webpack5

### Expected Behavior
Filename as output config specified.

### Actual Behavior
Filename with auto prefix.

**Comment by shellscape** [comment]
Please search before opening new issues. This has been discussed many times.

**Comment by mariusGundersen** [comment]
I searched and found this issue. Please link to proper issue

**Comment by G-Rath** [comment]
Ref: https://github.com/shellscape/webpack-manifest-plugin/issues/229#issuecomment-737617994
