### ISSUE TITLE
document usage of writeToFileEmit with webpack-clean plugin

### ISSUE THREAD

**Issue by devkral** [shellscape/webpack-manifest-plugin#267]
- Manifest Plugin Version:
3.1.1

Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
webpack-clean plugin deletes manifest.json if used with webpack-dev-server.
It should be documented that you have to exclude manifest.json like this
```javascript
new CleanWebpackPlugin({
            verbose: true,
//important elsewise minifest.json is deleted
            cleanOnceBeforeBuildPatterns: ['**/*', '!manifest.json'],
        }),
```

**Comment by shellscape** [comment]
Thanks, I'll add this to the README.

**Comment by gaurav5430** [comment]
Thanks, this saved me from opening a new issue for manifest not being generated with webpack-dev-server
