### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Lijiaoa** [shellscape/webpack-manifest-plugin#269]
- Manifest Plugin Version: ^3.1.1
- Webpack Version:  ^5.39.0
- Operating System (or Browser): unbuntu
- Node Version: 16.3.0
- Link to reproduction _(⚠️ read below)_: 

### Actual Behavior
in develop env, yarn start will met this error:

![image](https://user-images.githubusercontent.com/61399850/125719379-a30fa21f-d386-4dc9-ab5f-a25566fd2401.png)

### Additional Information
`path: isEnvProduction ? paths.appBuild : undefined,` in webpack.config.js caused this issue, but i don't know how to deal with it.

**Comment by Omelettesheep** [comment]
same problem

**Comment by shellscape** [comment]
No reproduction, closing.
