### ISSUE TITLE
index.ts should use esm syntax and compile to cjs if necessary

### ISSUE THREAD

**Issue by Artoria-0x04** [shellscape/webpack-manifest-plugin#273]
- Manifest Plugin Version: 4.0.1

### Expected Behavior / Situation
Plugin can be used with both
`import { WebpackManifestPlugin } from "webpack-manifest-plugin";`
and
`const { WebpackManifestPlugin } = require("webpack-manifest-plugin");`

### Actual Behavior / Situation
`WebpackManifestPlugin` is not exported when using import, not shown in index.d.ts of course.

### Modification Proposal
Use esm syntax named export in source code, then compile to cjs if necessary

**Comment by shellscape** [comment]
Sure, open a PR. Pretty simple change.

**Comment by shellscape** [comment]
Some other types needed improvement, so this was handled in 098b6ddbea8640f008cf5d786f7ae9d12cc54bb8
