### ISSUE TITLE
Please support lower versions of Node 12

### ISSUE THREAD

**Issue by alexbbt** [shellscape/webpack-manifest-plugin#274]
- Manifest Plugin Version: 4.0.2

### Expected Behavior / Situation
Support for node 12.

### Actual Behavior / Situation
Requires node 12.22 or greater. We are using node 12.18 in production and do not want to switch any time soon. 

### Modification Proposal
``` diff
"engines": {
-    "node": ">=12.22.0"
+    "node": ">=12.18.0"
  },
```

This could also be a more inclusive version change, if you wanted to support more versions of node.

**Comment by shellscape** [comment]
sorry. I politely decline. if you have the need to use an outdated version of node, please fork and change package JSON to meet your needs

**Comment by shellscape** [comment]
Or of course, v3.x still supports Node v10, but will not be receiving updates.

**Comment by alexbbt** [comment]
Yeah, we are using webpack 5, which I know makes it silly that we are stuck on and old version of node. I'm working to upgrade our systems but figured I would check in case you meant to support all of node 12.
