### ISSUE TITLE
Fix `fileName` option to not conflict with the real manifest.json

### ISSUE THREAD

**Issue by dPowNextdoor** [shellscape/webpack-manifest-plugin#275]
- Manifest Plugin Version: Current

### Expected Behavior / Situation

WebpackManifestPlugin is actually an [assets manifest](https://github.com/facebook/create-react-app/issues/6436), i.e. just a log of files. As such, its output file name should reflect that.

### Actual Behavior / Situation

The plugin outputs assets info into `manifest.json`, breaking web standards and not creating a [correct manifest.json](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json). Not to mention that outputting this info to `manifest.json` is misleading to new devs.

### Modification Proposal

Update the default `fileName` to `assets-manifest.json`.

**Comment by shellscape** [comment]
thanks for opening an issue. unfortunately it's not a change that I'm interested in at this point

**Comment by javierguzman** [comment]
Sorry to ask here but I have not found any response after hours of search. Is there a way to make webpack-manifest-plugin generate a real/correct manifest.json? Or does it only create the assets-manifest.json? If it only generates the assets-manifest.json, what is normally done to create the real manifest.json? I feel this plugin would be suitable for generating the real manifest.json as well as it knows all hashed images names, etc. Thank you in advance and regards
