### ISSUE TITLE
request modification for the destructive type change from v4.0.2

### ISSUE THREAD

**Issue by hagevvashi** [shellscape/webpack-manifest-plugin#278]
- Manifest Plugin Version: 4.0.2

### Expected Behavior / Situation

generate function should returns `Record<string, unknown>` or simply any because the document says `A custom Function to create the manifest. The passed function should match the signature of (seed: Object, files: FileDescriptor[], entries: string[]) => Object and can return anything as long as it's serialisable by JSON.stringify.`.

https://github.com/shellscape/webpack-manifest-plugin/blob/77eca2545b70ea235fc2c6b5ddf0f90540dd8588/README.md#generate

FYI

We use custom webpack-plugin (this is the patch for webpack-manifest-plugin) for the split-chunks-plugin.

For example, expected the manifest.json's content is below.

```json
{
  "entry1": [
    "https://example.com/646-3897fzafiawef87c.js"
    "https://example.com/foo-fajewu3i3uqr11.js"
  ],
  "entry2": [
    "https://example.com/646-3897fzafiawef87c.js",
    "https://example.com/bar-083asfd8734f.js"
  ]
}
```

### Actual Behavior / Situation

generate function's return type is `Record<string, string>`.

From [this commit](https://github.com/shellscape/webpack-manifest-plugin/commit/098b6ddbea8640f008cf5d786f7ae9d12cc54bb8)

### Modification Proposal

1. Could you revert https://github.com/shellscape/webpack-manifest-plugin/commit/098b6ddbea8640f008cf5d786f7ae9d12cc54bb8 ?
2. Could you change the `Manifest` to `Record<string, unknown>` ?

**Comment by shellscape** [comment]
There needs to be compelling community-wide reasoning for reverting a valid fix. I don't think this qualifies. More appropriate would be a documentation update (in which case I'd consider a PR). If you need to return something through generate that is unexpected, then use `return resultThing as any`, or cast to `unknown` first.

**Comment by hagevvashi** [comment]
@shellscape 
Thanks for the reply, I understand about the revert.
What about my suggestion `Could you change the Manifest to Record<string, unknown>` ?

When you say update the documentation, do you mean that the type definition is correct? I think `Record<string, unknown>` is better, because `Record<string, string>` has limited usage.
