### ISSUE TITLE
Module not found: Error: Can't resolve....

### ISSUE THREAD

**Issue by elubin** [shellscape/webpack-manifest-plugin#288]
I am running the plugin against a hello world project. My main.ts contains 2 imports that return this error when running 'npx wp'. The app runs local and those imports are resolved. Do I need to tell the plugin a path? The app directory is definitely in the src directory.

main.ts
```
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
```

error
```
ERROR in ./src/main.ts
  Module not found: Error: Can't resolve './app/app.module' in 'C:\src\micro-dashboard\src'
   @ ./src/main.ts 4:0-45 11:41-50
   @ multi ./src/main.ts

  ERROR in ./src/main.ts
  Module not found: Error: Can't resolve './environments/environment' in 'C:\src\micro-dashboard\src'
   @ ./src/main.ts 5:0-57 7:4-15
   @ multi ./src/main.ts

```

**Comment by shellscape** [comment]
>   🚨 Your issue will be CLOSED if:
>      - This template is removed
>      - Parts of this template are removed
> 
>   👉🏽 Need help or tech support? Please don't open an issue!
>   Head to https://gitter.im/webpack/webpack or https://stackoverflow.com/questions/tagged/webpack
