### ISSUE TITLE
Clarify "evergreen" policy's relation to semver

### ISSUE THREAD

**Issue by strugee** [shellscape/webpack-manifest-plugin#298]
- Manifest Plugin Version: N/A

Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

It's unclear to me whether dropping support for non-active LTS node versions would trigger a bump of this library's major version (or actually whether the library conforms to semantic versioning at all, though based on GitHub Releases I'm guessing that it does).

I have read the FAQ and skimmed GitHub releases and the README for this info.

### Your Proposal for Changes

Honestly, I'm not quite sure. Maybe put it in the FAQ? The best place for this is probably [CHANGELOG.md](https://keepachangelog.com/en/1.0.0/), but this project uses GitHub Releases instead (note that there's an FAQ on that website about GitHub Releases). Here's an example: https://github.com/pump-io/pump.io/blob/master/CHANGELOG.md

**Comment by strugee** [comment]
Sorry, to further clarify - the reason this is confusing is because "you need x, y or z Node versions, which happen to be active LTS versions at the time of writing" being part of the interface contract is very different from "you need an active LTS version". The latter implies to me that dropping an unmaintained Node version wouldn't be semver-major.

**Comment by shellscape** [comment]
I think you're thinking too much about this. it's a general statement, the source of truth is package.json.

**Comment by strugee** [comment]
Hmm, maybe :P looking at `package.json` certainly helps.

It still doesn't really answer my question though - basically I want to know if Node versions being dropped will be noted as a breaking change in the changelog.
